
# Example list of keywords for variety
IMAGE_KEYWORDS = [
    "grind",
    "determination",
    "focused mindset",
    "building wealth",
    "long-term goals",
    "consistent effort",
    "power of discipline",
    "daily hustle",
    "inner strength",
    "entrepreneurial spirit",
    "investment journey",
    "humble success",
    "hard-earned achievement",
    "financial wisdom",
    "legacy creation",
    "self-reliance",
    "financial literacy",
    "passionate work",
    "sustained effort",
    "personal discipline",
    "wealth building habits",
    "smart decisions",
    "growth mindset",
    "quiet power",
    "delayed gratification",
    "sacrifices for success",
    "humble work ethic",
    "true wealth",
    "steady progress",
    "success through effort",
    "investing in self"
]

VIDEO_KEYWORDS = [
    "financial",
    "hard work",
    "growth",
    "success",
    "humble",
    "business",
    "determined",
    "professional",
    "entrepreneur",
    "wealth",
    "ambitious",
    "powerful",
    "decisions",
    "grind",
    "grit",
    "confidence",
    "calm",
    "life lessons",
    "discipline",
    "hard earned",
    "strength",
    "pursuit",
    "motivation",
    "leadership",
    "teamwork",
    "vision",
    "resilience",
    "mindset",
    "focus",
    "overcoming",
    "opportunities",
    "innovation",
    "strategy",
    "balance",
    "perseverance",
    "hustle",
    "creativity",
    "determination",
    "goal setting",
    "self-made",
    "personal",
    "empowerment",
    "mentorship",
    "legacy",
    "passion",
    "dedication",
    "purpose",
    "achievement"
]

VIDEO_KEYWORDS_FUN = [
    "funny",
    "hilarious",
    "comedy",
    "laugh",
    "jokes",
    "entertainment",
    "humor",
    "puns",
    "skits",
    "pranks",
    "giggles",
    "witty",
    "relatable",
    "meme",
    "banter",
    "sarcasm",
    "silly",
    "LOL",
    "fun",
    "chuckle",
    "gags",
    "zany",
    "antics",
    "light-hearted",
    "unexpected",
    "awkward",
    "laugh out loud",
    "hilarious moments",
    "snappy",
    "over the top",
    "ridiculous",
    "timing",
    "situational comedy",
    "one-liners",
    "crazy",
    "good vibes",
    "improv",
    "parody",
    "absurd",
    "mischief",
    "shtick",
    "sketches",
    "relatable humor",
    "feel-good fun"
]

VIDEO_KEYWORDS_FUN_FACTS = [
    "running",
    "happy",
    "working",
    "swimming",
    "laugh",
    "acting",
    "entertainment",
    "unbelievable",
    "unusual trivia",
    "curious",
    "hidden knowledge",
    "curiosity",
    "oddities",
    "fun and educational",
    "learn something new",
    "unknown secrets",
    "educational and fun",
    "mind-expanding trivia",
    "crazy",
    "good vibes"
]
